name: build_and_test

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - name: Windows
          run: |
            python fips build
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
        - name: macOS
          run: |
            python fips build
